---
title: 'AEM Replication: 1'
author: "Maxwell Austensen"
date: '`r Sys.Date()`'
output:
  github_document: default
  html_notebook: default
---


```{r, message=FALSE, warning=FALSE, include=FALSE}
# Install packages if needed
package_list <- c("haven", "stringr", "tidyverse", "janitor", "feather", "knitr", "rmarkdown")
new_packages <- package_list[!package_list %in% installed.packages()[,"Package"]]
if(length(new_packages)) install.packages(new_packages)

library(haven)
library(stringr)
library(tidyverse)
library(janitor)
library(feather)

# Set directories
raw_ <- "/Users/Maxwell/Box Sync/aem/replication/data/raw/"
clean_ <- "/Users/Maxwell/Box Sync/aem/replication/data/clean/"
```

```{r}
raw <- read_stata(str_c(raw_, "usa_00005.dta"))
```

```{r}
names(raw) <- names(raw) %>% str_to_lower()
raw <- raw %>% zap_labels()
raw %>% select(noquote(order(colnames(raw)))) %>% glimpse()
```

```{r}
mothers <- 
  raw %>%
  group_by(serial) %>% 
  mutate( # Create standardized household income - needs info on all hh members
          adults = sum(age >= 18, na.rm = TRUE),
          children = sum(age < 18, na.rm = TRUE),
          inc_adjuster = ((adults + (0.7 * children)) ^ 0.7),
          hhincome_std = hhincome / inc_adjuster) %>% 
  ungroup() %>% 
  filter( # restrict sample
          between(bpl, 1, 120), # US born (inc'l us territories etc.)
          race == 1, # white
          sex == 2, # female
          between(age, 21, 40), # age 21-40
          between(marrno, 1, 2), # ever married
          between(agemarr, 17, 26), # married age 17-26
          between(chborn, 2, 13), # ever child
          between(marst, 1, 4), # ever married but not widow
          qage == 0, # not allocated: age
          qchborn == 0, # not allocated: chilren born
          qmarrno == 0, # not allocated: married
          qmarst == 0, # not allocated: marital status
          qagemarr== 0, # not allocated: married age
          qrelate == 0, # not allocated: relation to household head
          qsex == 0) # not allocated: sex

nrow(mothers)
```

```{r}
children <-
  raw %>% 
  filter(momloc != 0) %>% 
  group_by(serial, momloc) %>% 
  mutate(children_hh  = n()) %>% # number of mother's children in household
  filter(age == max(age)) %>% # Keep only the oldest (can be multiple oldest if same age in years)
  mutate(max_age = max(age),
         same_qtr = sum(birthqtr == lag(birthqtr), na.rm = TRUE),
         twin1 = if_else(n() > 1, 1, 0), # twin based only on age in years
         twin2 = if_else(same_qtr > 0, 1, 0)) %>% # twin based on age in years and quarter
         # note: "twin" also includes other multiples (eg. triplets) 
  arrange(serial, desc(age), birthqtr) %>% 
  filter(row_number() == 1) %>% # keep only one child if twin
  ungroup()

names(children) <- names(children) %>% map_chr(~ str_c(.x, "_c"))

# children %>% get_dupes(serial, momloc) # no dupes

nrow(children)
```

```{r}
sample1 <-
  left_join(mothers, children, by = c("serial" = "serial_c", "pernum" = "momloc_c")) %>%
  filter(is.na(qage_c) | qage_c == 0, # not allocated: child's age
         is.na(qsex_c) | qsex_c == 0, # not allocated: child's sex
         is.na(qrelate_c) | qrelate_c == 0, # not allocated: child's relation to head of household
         is.na(qbirthmo_c) | qbirthmo_c == 0) %>% # not allocated: child's birth month
  filter(# bpl <= 56,
         # bpl %in% c(1:56, 110),
         raced == 100) %>%
  mutate(marr_ended = if_else(marst %in% c(3, 4) | marrno == 2, 1, 0),
         firstborn_girl = if_else(sex_c == 2, 1, 0),
         educ_yrs = if_else(higrade < 4, 0, higrade - 3),
         age_birth = age - age_c,
         age_married = agemarr,
         urban = if_else(metarea == 0, 0, 1),
         n_children = if_else(chborn < 2, 0, chborn - 1),
         poverty_status = if_else(is.na(poverty), NA_real_, if_else(poverty < 100, 1, 0)),
         nonwoman_inc = hhincome - inctot,
         woman_inc = inctot,
         woman_earn = incwage,
         employed = if_else(empstat == 1, 1, 0),
         worked_wks = if_else(wkswork1 == 00, NA_real_, wkswork1),
         worked_hrs = if_else(uhrswork == 00, NA_real_, uhrswork)) %>%
  select(serial,
         pernum,
         perwt,
         marr_ended,
         firstborn_girl,
         educ_yrs,
         age_birth,
         urban,
         n_children,
         hhincome_std,
         poverty_status,
         nonwoman_inc,
         woman_inc,
         woman_earn,
         employed,
         worked_wks,
         worked_hrs,
         chborn,
         age,
         children_hh_c,
         age_c,
         twin1_c,
         twin2_c)

# get_dupes(sample1, serial) # no dupes

# Paper results: 662,204
nrow(sample1)
```

```{r}
sample2 <- 
  sample1 %>% 
  mutate(children_ever = if_else(chborn == 13, NA_real_, chborn - 1)) %>% 
  filter(children_ever == children_hh_c, age_c < 18, twin2_c != 1)

# Paper results: 535,887
nrow(sample2)
```

```{r}
sample3 <-
  sample2 %>% 
  mutate(marr_len = age - agemarr,
         marr_yr_born = marr_len - age_c) %>% 
  filter(between(marr_yr_born, 0, 5)) %>%
  select(-marr_len, - marr_yr_born)

# Paper results: 465,595
nrow(sample3)
```

```{r}
  write_feather(sample1, str_c(clean_, "sample1.feather"))
  write_feather(sample2, str_c(clean_, "sample2.feather"))
  write_feather(sample3, str_c(clean_, "sample3.feather"))
```



