---
title: 'AEM Replication: 2'
author: "Maxwell Austensen"
date: '`r Sys.Date()`'
output:
  github_document: default
  html_notebook: default
---


```{r, message=FALSE, warning=FALSE, include=FALSE}
# Install packages if needed
package_list <- c("haven", "stringr", "tidyverse", "janitor", "feather", "knitr", "rmarkdown")
new_packages <- package_list[!package_list %in% installed.packages()[,"Package"]]
if(length(new_packages)) install.packages(new_packages)

library(haven)
library(stringr)
library(tidyverse)
library(janitor)
library(feather)

# Set directories
clean_ <- "/Users/Maxwell/Box Sync/aem/replication/data/clean/"
```

```{r}
sample1 <- read_feather(str_c(clean_, "sample1.feather")) %>% mutate(sample = "Sample 1")
sample2 <- read_feather(str_c(clean_, "sample2.feather")) %>% mutate(sample = "Sample 2")
sample3 <- read_feather(str_c(clean_, "sample3.feather")) %>% mutate(sample = "Sample 3")
```

```{r}
format_sd <- function(x, digits = 2) {
  x %>% round(digits = digits) %>% str_c("(", ., ")")
}

format_mean <- function(val, digits = 2) {
  val %>% round(digits = digits) %>% as.character()
}
```

```{r, message=FALSE, warning=FALSE}

order_vec <- c("marr_ended_mean", "marr_ended_sd", "agemarr_mean", "agemarr_sd", "child_girl_mean", 
               "child_girl_sd", "chborn_mean", "chborn_sd", "age_birth_mean", "age_birth_sd", "age_mean", 
               "age_sd", "educ_yrs_mean", "educ_yrs_sd", "urban_mean", "urban_sd", "hhincome_std_mean", 
               "hhincome_std_sd", "poverty_status_mean", "poverty_status_sd", "nonwoman_inc_mean", 
               "nonwoman_inc_sd", "woman_inc_mean", "woman_inc_sd", "woman_earn_mean", "woman_earn_sd", 
               "obs_mean", "obs_sd")

bind_rows(sample1, sample2, sample3) %>% 
  group_by(sample) %>% 
  mutate(marr_ended = if_else(marst %in% c(3, 4) | marrno == 2, 1, 0),
         age_birth = age - age_c,
         child_girl = if_else(sex_c == 2, 1, 0),
         educ_yrs = if_else(higrade <= 3, 0, higrade - 3),
         urban = if_else(metarea == 0, 0, 1),
         poverty_status = if_else(is.na(poverty), NA_real_, if_else(poverty < 100, 1, 0)),
         nonwoman_inc = hhincome - inctot,
         woman_inc = inctot,
         woman_earn = incwage,
         obs = n()) %>% 
  select(marr_ended, agemarr, child_girl, chborn, age_birth, age, educ_yrs, urban, 
         hhincome_std, poverty_status, nonwoman_inc, woman_inc, woman_earn, obs) %>% 
  summarise_all(funs(mean, sd)) %>%
  mutate_at(vars(contains("_mean")), format_mean) %>%
  mutate_at(vars(contains("_sd")), format_sd) %>%
  gather("variable", "value", -sample) %>% 
  spread(sample, value) %>% 
  mutate(variable = ordered(variable, levels = order_vec)) %>% 
  arrange(variable) %>% 
  filter(variable != "obs_sd") %>% 
  mutate(variable = str_replace(variable, "_mean", ""),
         variable = if_else(str_detect(variable, "_sd"), "", variable)) %>% 
  knitr::kable()
```

