---
title: '6: Table 5 - Divorce Effect by Firstborn Age'
author: "Maxwell Austensen"
date: '`r Sys.Date()`'
output:
  github_document: default
  html_notebook: default
subtitle: AEM Replication
---

```{r, message=FALSE, warning=FALSE, include=FALSE}
# Install packages if needed
package_list <- c("haven", "stringr", "tidyverse", "janitor", "feather", "knitr", "rmarkdown")
new_packages <- package_list[!package_list %in% installed.packages()[,"Package"]]
if(length(new_packages)) install.packages(new_packages)

library(haven)
library(stringr)
library(tidyverse)
library(feather)
library(broom)
library(sandwich)

# Set directories
clean_ <- "C:/Users/austensen/Box Sync/aem/replication/data/clean/"
# clean_ <- "/Users/Maxwell/Box Sync/aem/replication/data/clean/"
```

```{r}
sample3 <- read_feather(str_c(clean_, "sample3.feather"))
```


```{r}
get_estimates <- function(p, data, adj, extra_adj = FALSE){
  covariates <- " + age + age_birth + age_married + educ_yrs + I(age^2) + I(age_married^2) + I(age_birth^2) + I(educ_yrs^2) + age*educ_yrs + age_married*educ_yrs + age_birth*educ_yrs + urban + factor(state_birth) + factor(state_current)"
  
  if(adj){
    if(extra_adj){
      f <- str_interp("${p} ~ marriage_ended ${covariates} + n_children + marital_status")
    } else {
      f <- str_interp("${p} ~ marriage_ended ${covariates}")
    }
  } else {
    f <- str_interp("${p} ~ marriage_ended")
  }

  mod <- lm(formula = f, data = data)

  # Robust stanadard errors (replicating Stata's robust option)
  robust_se <- 
    mod %>% 
    vcovHC(type = "HC1") %>% 
    diag() %>% 
    sqrt() %>% 
    .[[2]]

  mod %>% 
    tidy() %>% 
    filter(term == "marriage_ended") %>% 
    transmute(var = p,
              est = estimate,
              se = robust_se) %>% 
    gather("stat", "value", -var) %>% 
    unite(variable, var, stat)
}
```

```{r}
econ_vars <- c("hh_income_std", "poverty_status", "nonwoman_inc", "woman_inc", "woman_earn", "employed", "weeks_worked", "hours_worked")

ols_table1 <- 
  econ_vars %>% 
  map_df(get_estimates, data = sample3, adj = TRUE) %>% 
  rename(OLS = value)
```






