---
title: '7: All Tables'
author: "Maxwell Austensen"
date: '`r Sys.Date()`'
output:
  html_document: default
  github_document: default
  html_notebook: default
subtitle: AEM Replication
---

***

```{r, message=FALSE, warning=FALSE, include=FALSE}
# Install packages if needed
package_list <- c("tidyverse", "stringr", "feather", "knitr", "rmarkdown")
new_packages <- package_list[!package_list %in% installed.packages()[,"Package"]]
if(length(new_packages)) install.packages(new_packages)

library(stringr)
library(tidyverse)
library(feather)
library(xtable)
library(knitr)

# Set directories
clean_ <- "/Users/Maxwell/Box Sync/aem/replication/data/clean/"
```


```{r, echo=FALSE}
table1 <- read_feather(str_c(clean_, "tables/table1.feather"))
table2 <- read_feather(str_c(clean_, "tables/table2.feather"))
table3 <- read_feather(str_c(clean_, "tables/table3.feather"))
table4 <- read_feather(str_c(clean_, "tables/table4.feather"))
table5 <- read_feather(str_c(clean_, "tables/table5.feather"))
```

```{r, echo=FALSE}
options(knitr.kable.NA = "")
```

```{r, echo=FALSE}
title1 <- "Table 1: Descriptive Statistics"

table1 %>% 
  mutate(variable = if_else(str_detect(variable, "_sd"), "", variable),
         variable = str_replace(variable, "_mean", "")) %>%
  kable(caption = title1, digits = 2, format.args = list(big.mark = ','))
```

***

```{r, echo=FALSE}
title2 <- "Table 2: Effect of Firstborn Sex on the Probability of Marital Instability"
knitr::kable(table2, caption = title2, digits = c(NA, 3, 1, 3, 1, 0), format.args = list(big.mark = ','))
```

***

```{r, echo=FALSE}
title3 <- "Table 3: Differences in Means, by Divorce Status and Firstborn Sex (Ever-Married Mothers)"

table3 %>% 
  mutate(variable = as.character(variable),
         variable = if_else(str_detect(variable, "_two"), "", variable),
         variable = str_replace(variable, "_one", "")) %>%
  kable(caption = title3, digits = 3)
```

***

```{r, echo=FALSE}
title4 <- "Table 4: The Effect of Divorce on Female Economic Status and Labor Supply"

table4 %>% 
  mutate(variable = if_else(str_detect(variable, "_se"), "", variable),
         variable = str_replace(variable, "_est", "")) %>%
  kable(caption = title4, digits = 3)
```

***

```{r, echo=FALSE}
title5 <- "The Effect of Divorce on Female Economic Status and Labor Supply,
by Firstborn Age"

table5 %>% 
  mutate(variable = if_else(str_detect(variable, "_se"), "", variable),
         variable = str_replace(variable, "_est", "")) %>%
  kable(caption = title5, digits = 3, format.args = list(big.mark = ','))
```



